apiVersion: v1
kind: Service
metadata:
  name: my-static-site-service
spec:
  selector:
    app: my-static-site
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32767  # access via localhost:30080
